### ISSUE TITLE
add support for badging API

### ISSUE THREAD

**Issue by evdama** [kevmodrome/svelte-favicon-badge#1]
As mentioned on discord this morning, you could add support for the up and coming **badging API** which would make this component even better because it would also include the ability to have app badges (the notification your app icon would show) in addition to notifications on top or next to the favicon in the browser tab.

https://github.com/WICG/badging/blob/master/explainer.md

`setAppBadge()` is implemented on Chrome Canary already, `setClientBadge()` will follow soon.

The concept of the badging API would basically, semantically wrap your component such as

```js
function unreadCountChanged(newUnreadCount) {
  // Set the app badge, for app icons and links. This has a global and
  // semi-permanent effect, outliving the current document.
  if (navigator.setAppBadge) {
    navigator.setAppBadge(newUnreadCount);
  }

  // Set the document badge, for the current tab / window icon.
  if (navigator.setClientBadge) {
    navigator.setClientBadge(newUnreadCount);
  } else {
    // Fall back to setting favicon (or page title).
    // (This is a user-supplied function, not part of the Badge API.)
    showBadgeOnFavicon(newUnreadCount);  <--- this is where your component would kick in if no support for badging API in the browser yet
  }
}
```

With, for example, `$newUnreadCount` being a reactive variable, one can see the coolness factor of that stuff :yum:

I tested and love set/clearAppBadge() with my progressive web app... it would litteraly show the unread count in the app icon inside my dock on mac os even when the app isn't open

**Comment by kevmodrome** [comment]
Is this something you would be interested in doing a PR for?

**Comment by kevmodrome** [comment]
Closing this since it's stale

**Comment by evdama** [comment]
> Is this something you would be interested in doing a PR for?

yes, I just haven't gotten around to it yet 🥴
